### PR TITLE
Update variables to work with the ansible setting 'inject_facts_as_vars' set to False

### PR DESCRIPTION
**Pull request by misuto**
Some variables are referenced by the name `ansible_` which is only set when the config option 'inject_facts_as_vars' is set to True (which is is by default). If this option is set to false this role stops working. The solution is to reference the variable by their full fact name (`ansible_fact.<variable name>`).  
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#inject-facts-as-vars  
https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#when-is-it-unsafe-to-bulk-set-task-arguments-from-a-variable

### CODE REVIEW

**Comment by utkuozdemir** [comment]
Thanks for the PR. There seems to be some problem with the build but it's not on your side. I'm trying to fix it - when I'm done with it, we can rebase and get this tested.

**Comment by misuto** [comment]
Sounds good! Just write here when you are done and I will rebase :+1:

**Comment by utkuozdemir** [comment]
You can already do it :)

**Comment by utkuozdemir** [comment]
Ok, DigitalOcean is acting weird, I'll need to have a further look.

**Comment by misuto** [comment]
No problem, just write here when it's ready for another rebase.

**Comment by utkuozdemir** [comment]
I think you can now rebase again

**Comment by misuto** [comment]
Still seems like the test does not work

**Comment by utkuozdemir** [comment]
Oh, I see, the issue was this all along 🤦  https://github.community/t/make-secrets-available-to-builds-of-forks/16166/32

Since the local tests are passing, I'll go ahead and merge them. For the external test, I'll later try to exclude them from running if PR is coming from a fork.

Thanks for the contribution!

**Pull request merged**
